document.writeln('<footer>');
document.writeln('    <ul class="foot_ope flex">');
document.writeln('        <li><a>隐私政策</a></li>');
document.writeln('        <li><a href="about.html">关于我们</a></li>');
document.writeln('       <li><a>联系我们</a></li>');
document.writeln('    </ul>');
document.writeln('    <p>客服电话：010-51608888 总部地址：北京市海淀区中关村大街49号大华科技商厦二层 巨人教育</p>');
document.writeln('    <p>京ICP备15063787号-15 | 京ICP证B2-20180662号 | 京公网安备11010802024709号</p>');
document.writeln('    <p>Copyright ©1994-2020 巨人教育 JUREN.com 版权所有</p>');
document.writeln('</footer>');